### PR TITLE
geor_urbanisme_mapstore_v1.0.0

### PR DESCRIPTION
**Pull request by nrc97**

### CODE REVIEW

**Comment by jusabatier** [comment]
It look like those changes involve also changes for backend implementation. Can them be documented ?

I remind you that there are multiple implementations for backend and they both need to be upgraded to support this upgrade.

In order to be able to upgrade them, we need documentations abouts changes, specially if they impact API.

**Comment by ThomasBruleOpen** [comment]
Hi Julien, 

There is no changes from backoffice impacting the frontoffice : it was one of our requirement. 

By consequence, if you deploy new version of the backoffice, your frontoffice will be operationnal as it.

**Comment by jusabatier** [comment]
I wonder more about the compatibility of the new frontoffice with old backoffice API ?

**Comment by sigrmed** [comment]
When deploying the new frontoffice, a new parameter drive the call to the old road to get NRU datas or to the new road to get NRU datas :
`    "urbanismeRenseignGroupe": true|false`

If true, build call to PDF with news paramters
If false, build call to PDF with old parameters, as actually.

Anyway, this pull request is cancelled, replaced by a new one.

**Pull request closed without merging**
